### ISSUE TITLE
the issue on the kx_array

### ISSUE THREAD

**Issue by rayyyyy** [zhaonat/Rigorous-Coupled-Wave-Analysis#2]
Hello! A wonderful work on RCWA, but I am curious about the kx_array, which in the RCWA_1D_functions\TM_solver.py is kx_array = k0*(n1*np.sin(theta) + indices*(lam0 / lattice_constant)). The reference paper writes that kx_array = k0*(n1*np.sin(theta) - indices*(lam0 / lattice_constant)), which differs from your code by the "minus". I wonders what is right.

**Comment by zhaonat** [comment]
indices is an array with numbers from -n, -n+1, ... , n-1, n so because of this, using a minus sign or a plus sign actually does not change anything.

**Comment by rayyyyy** [comment]
> indices is an array with numbers from -n, -n+1, ... , n-1, n so because of this, using a minus sign or a plus sign actually does not change anything.

OK，I understand, Thank you for your help!
